### ISSUE TITLE
Incompatibility with PS 2.0

### ISSUE THREAD

**Issue by jdthorpe** [9to5IT/PSLogging#1]
Thanks for the great logging package!  With Powershell 2.0, when I call:

	PS > Import-Module pslogging

I get the following error the following error:

	Import-Module : The '~\Documents\WindowsPowerShell\Modules\pslogging\pslogging.psd1' 
	module cannot be imported because its manifest contains one or more members 
	that are not valid. The valid manifest members are (--list-of-members--). 
	Remove the members that are not valid ('RootModule', 'HelpInfoURI'), then try 
	to import the module again. 

In powershell 2.0 the equivalent of "RootModule" is "ModuleToProcess", and there is no equivalent to "HelpInfoURI".  Fortunately, renaming "RootModule" as "ModuleToProcess" and commenting out "HelpInfoURI" did the trick.  

This issue could be resolved by mentioning these changes that are required for PS 2.0 in your README.md  

Also, in case it's useful for identifying versions of PS to which these changes apply, here is my `$PSVersionTable`: 

Name                           Value
----                           -----
CLRVersion                     2.0.50727.5485
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1

**Comment by 9to5IT** [comment]
Hi jdthorpe,

Sorry about the late reply, I was overseas and didn't get much time to check emails, etc.

Thanks very much for the info, I will look into it and update the doco.

Thanks again!
Luca
